safe: true
pygments: true
permalink: /archives/:title/

author: Infong
title: A good memory as bad written.
email: clarelyf@gmail.com

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-24623558-3

github:
  username: infong

disqus:
   id: agoodmemoryasbadwritten
